// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportProfileFromCurrentAuth(arg1) {
  return window['go']['main']['App']['ImportProfileFromCurrentAuth'](arg1);
}

export function ImportProfileFromFile(arg1) {
  return window['go']['main']['App']['ImportProfileFromFile'](arg1);
}

export function ImportProfileFromRaw(arg1) {
  return window['go']['main']['App']['ImportProfileFromRaw'](arg1);
}

export function ListAuditLogs() {
  return window['go']['main']['App']['ListAuditLogs']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function PickAuthPath() {
  return window['go']['main']['App']['PickAuthPath']();
}

export function PickImportFile() {
  return window['go']['main']['App']['PickImportFile']();
}

export function ReorderProfiles(arg1) {
  return window['go']['main']['App']['ReorderProfiles'](arg1);
}

export function RunDiagnostics() {
  return window['go']['main']['App']['RunDiagnostics']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
