// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {detector} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfile(arg1:string):Promise<main.ProfileDTO>;

export function GetSettings():Promise<config.Settings>;

export function ImportProfileFromCurrentAuth(arg1:main.ImportProfileInput):Promise<main.ProfileDTO>;

export function ImportProfileFromFile(arg1:main.ImportProfileFromFileInput):Promise<main.ProfileDTO>;

export function ImportProfileFromRaw(arg1:main.ImportProfileFromRawInput):Promise<main.ProfileDTO>;

export function ListAuditLogs():Promise<Array<main.AuditEntryDTO>>;

export function ListProfiles():Promise<Array<main.ProfileDTO>>;

export function PickAuthPath():Promise<string>;

export function PickImportFile():Promise<string>;

export function ReorderProfiles(arg1:Array<string>):Promise<Array<main.ProfileDTO>>;

export function RunDiagnostics():Promise<detector.Diagnostics>;

export function SaveSettings(arg1:config.Settings):Promise<config.Settings>;

export function SwitchProfile(arg1:string):Promise<main.SwitchProfileResult>;

export function UpdateProfile(arg1:main.UpdateProfileInput):Promise<main.ProfileDTO>;
